package com.zx.pojo;

import java.util.Date;

public class Leavebill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.leaveBillId
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private Integer leavebillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.startTime
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.enTime
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private Date entime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.Cause
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private String cause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.day
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.lv
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private Integer lv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.state
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.userid
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leavebill.types
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    private String types;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.leaveBillId
     *
     * @return the value of leavebill.leaveBillId
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public Integer getLeavebillid() {
        return leavebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.leaveBillId
     *
     * @param leavebillid the value for leavebill.leaveBillId
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setLeavebillid(Integer leavebillid) {
        this.leavebillid = leavebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.startTime
     *
     * @return the value of leavebill.startTime
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.startTime
     *
     * @param starttime the value for leavebill.startTime
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.enTime
     *
     * @return the value of leavebill.enTime
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public Date getEntime() {
        return entime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.enTime
     *
     * @param entime the value for leavebill.enTime
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setEntime(Date entime) {
        this.entime = entime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.Cause
     *
     * @return the value of leavebill.Cause
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.Cause
     *
     * @param cause the value for leavebill.Cause
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.day
     *
     * @return the value of leavebill.day
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.day
     *
     * @param day the value for leavebill.day
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.lv
     *
     * @return the value of leavebill.lv
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public Integer getLv() {
        return lv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.lv
     *
     * @param lv the value for leavebill.lv
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setLv(Integer lv) {
        this.lv = lv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.state
     *
     * @return the value of leavebill.state
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.state
     *
     * @param state the value for leavebill.state
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.userid
     *
     * @return the value of leavebill.userid
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.userid
     *
     * @param userid the value for leavebill.userid
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leavebill.types
     *
     * @return the value of leavebill.types
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leavebill.types
     *
     * @param types the value for leavebill.types
     *
     * @mbggenerated Fri Sep 07 21:02:21 CST 2018
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }
}