package com.zx.pojo;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UserID
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UserName
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.RealName
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Email
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.State
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.AbteilungId
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private Integer abteilungid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.position
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.isLeadership
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    private Integer isleadership;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UserID
     *
     * @return the value of users.UserID
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UserID
     *
     * @param userid the value for users.UserID
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UserName
     *
     * @return the value of users.UserName
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UserName
     *
     * @param username the value for users.UserName
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.RealName
     *
     * @return the value of users.RealName
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.RealName
     *
     * @param realname the value for users.RealName
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Email
     *
     * @return the value of users.Email
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Email
     *
     * @param email the value for users.Email
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.State
     *
     * @return the value of users.State
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.State
     *
     * @param state the value for users.State
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.AbteilungId
     *
     * @return the value of users.AbteilungId
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public Integer getAbteilungid() {
        return abteilungid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.AbteilungId
     *
     * @param abteilungid the value for users.AbteilungId
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setAbteilungid(Integer abteilungid) {
        this.abteilungid = abteilungid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.position
     *
     * @return the value of users.position
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.position
     *
     * @param position the value for users.position
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.isLeadership
     *
     * @return the value of users.isLeadership
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public Integer getIsleadership() {
        return isleadership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.isLeadership
     *
     * @param isleadership the value for users.isLeadership
     *
     * @mbggenerated Fri Sep 07 20:46:08 CST 2018
     */
    public void setIsleadership(Integer isleadership) {
        this.isleadership = isleadership;
    }


}